server:
  port: 3359
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:F:/Spring_Boot_project_Sclar/H2_DB_blog_app/blog_app;
  jpa:
    hibernate:
      ddl-auto: create  #in prod use update , NOT create